### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by DmytroDidukh** [DmytroDidukh/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by dmytro-didukh** [comment]
-Hi there! I think I will couldn’t to introduce myself. I’m pretty sure if you are reading this on internet – you probably heard about me. Anyway, I would like to tell something…  When I was 20 years old, I have been launched Facebook from my room in Harvard university. And now – it’s one of the biggest IT corporation in the world. Every day I’m trying to do everything possible to make the world better, to make Facebook better and the most important thing is - to make life of Facebook’s user simpler and easier.
