### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by DmytroDidukh** [DmytroDidukh/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by dmytro-didukh** [comment]
. Facebook: www.facebook.com/theFacebookOwner. Instagram: www.instagram.com/MarkZuckerberg
LinkedIn: www.linkedin.com/mark_zuckerberg. Email: mark_zuckerberg@facebook.com
