### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by DmytroDidukh** [DmytroDidukh/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by dmytro-didukh** [comment]
•	Feb 4, 2004 – “The Facebook” launches (I, along with a group of friends launch Facebook from Harvard dormitory room. )
•	June 2004 – Drops out of Harvard (At that times – I was “felt in love” with “Facebook” and decided to leave university and devote myself full-time to my own project.)
•	Sep 23, 2005 – 5 million active users (That was amazing feeling to see how people likes what you did and makes you move forward)
•	2007 – Facebook is opened for anyone with an email address (From that time Facebook users didn’t need to get fully registration. To become a member – you just need an email)
•	2010 – Person of the Year ( 1. Time magazine names me Person of the Year. That was unexpected and I and I was confused. 2. David Fincher (one of the my favorite film director) released “The Social Network” – chronicling the early days of Facebook 3. Sings the “Giving Pledge”, and promising to donate at least 50 percent of my wealth to charity over the course of my lifetime)
•	2011 – Launch the Messenger
•	2012 – Facebook becomes a public company (That event increased my net worth to 17.5 billion dollars and that was good enough to releasing my ideas. Also that year, on May 19, I married with Priscilla Chan)
•	2014 – Acquisition of WhatsApp
•	2016 – Acquisition of Instagram
•	2017 – 1.5 billion of active users (Facebook is the greatest social network ever made 😊)
