### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by DmytroDidukh** [DmytroDidukh/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by dmytro-didukh** [comment]
1. Languages: English, Spanish, Chinese, Latin
2. Skills: Forward looking, Competent, Shared vision, lead change, set example, inspire people, empower people, honest
3. Character: Integrity, courage, accountability, humility, justice, temperance, caring
4. Likes: My wife, my son Max, tennis, programming, Chicken McNuggets, Taylor Swift, dogs, social networks, long shower, New York Times magazine, “eliminating desire”, Pablo Picasso
5. Dislikes: own bad habits, war, politics, lottery, alcohol, twitter
6. Wants: TO BE FIT AND HEALTHY, Facebook develop, to get 2 billion of active users, to learn, to explore the world
7. Education: 
- Sep, 1990 – May 1998 - Phillips Exeter Academy
- Sep, 1998 – June 2000 – Ardsley high School
- Aug, 2000 – July 2002 – Mercy Collage
- Sep, 2002 – April, 2004 – Harvard University (direction psychology and computer science)
